In [1]:
import numpy as np

## Note: LSS (least squares solution)

In [3]:
A = np.random.rand(4,5)
A

array([[0.08644348, 0.68235933, 0.25658305, 0.41350419, 0.61723471],
       [0.42438056, 0.43651038, 0.77505199, 0.94892243, 0.18129706],
       [0.04811642, 0.07017177, 0.79337106, 0.53776717, 0.71333962],
       [0.60045001, 0.38203266, 0.90375587, 0.8439884 , 0.21033215]])

In [4]:
b=np.array([0,0,0,1]).reshape(4,1)
b

array([[0],
       [0],
       [0],
       [1]])

In [10]:
x=np.linalg.lstsq(A,b,rcond=None)
x[0]

array([[ 3.33782634],
       [ 0.29203462],
       [ 1.08475591],
       [-2.61000918],
       [ 0.50728494]])

In [14]:
name2num={'Simone':0,"Archana":1,"Peter":2,"Scott":3}
num2name={v:k for k,v in name2num.items()}

In [12]:
name2num["Peter"]

2

In [15]:
num2name[3]

'Scott'

In [20]:
A = np.zeros((4,4))

In [17]:
A["Simone","Archana"]=4

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [18]:
A[ name2num["Simone"] , name2num["Archana"]]=4
A

array([[0., 4., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
mydict = {"Simone":["Archana","Archana","Peter"],"Peter":["Simone","Scott","Archana"]}

In [31]:
for k in mydict:
    s= set(mydict[k])
    for j in s:
        print(k,j,mydict[k].count(j))

Simone Peter 1
Simone Archana 2
Peter Scott 1
Peter Simone 1
Peter Archana 1
